# Generated by Django 4.0.2 on 2022-02-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_assignment_has_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AddField(
            model_name='page',
            name='page_num',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(default=-1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
