# Generated by Django 4.0.2 on 2022-02-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_page_image_page_page_num_page_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='path',
        ),
    ]
